name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        with:
          github_user_name: miaowumiaomiaowu
          outputs: |
            dist/github-contribution-grid-snake.svg
          # 自定义小蛇动画样式
          svg_border_radius: 4
          color_snake: #369cec
          color_dots: #8cc665
          color_empty: #ebedf0
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
